### ISSUE TITLE
希望添加一个全局可用的类似sleep休眠当前线程函数

### ISSUE THREAD

**Issue by JyenZhou** [smartmx/tiny-macro-os#1]
小小调度器那边实现的原理是延时函数中代替定时器调度任务
 这边看看有没有更好的方法  另外同步一下这个功能

**Comment by smartmx** [comment]
你指的功能难道不是这个函数：OS_TASK_WAITX

**Comment by JyenZhou** [comment]
不是的 你这个放在子函数中 也就是普通函数中无法用的  有交流群吗？这里我不怎么关注  我用小小调度器的做了个简单版本支持的  那边现在群都没了  也没人维护了  看到你这个基本一样的 就打算后面用你这个

**Comment by smartmx** [comment]
我这个就是用小小调度器发展来的。
普通函数支持调度？我没实现过，有参考吗？

**Comment by JyenZhou** [comment]
我可以发给你 你参考下底层逻辑  我写的用起来不是很优雅 另外根据一般使用习惯觉得您的有些函数是不是可以优化下  我的VX你加我下PRCPRCPRCPRCPRCPRC 昵称三个圈

**Comment by JyenZhou** [comment]
这个和watix有点像 只不过普通子函数能可用  类似sleep休眠当前线程  下面是楼主封装的 FUNC事实上就是所有任务 利用这里循环代替主程序中调度任务

//普通函数无阻塞延时 只能被主任务，以及主任务调用的函数，及主任务调用的函数调用的函数使用
#if COMPILER_SUPPORT_VA_ARGS
#define OS_HOLD_HERE(ANAME, TIMES, FUNC, ...)        		do{OS_TIMERS[(ANAME)]=TIMES;while(OS_TIMERS[(ANAME)] != 0){FUNC(__VA_ARGS__);}} while(0)
#else
#define OS_HOLD_HERE(ANAME, TIMES, FUNC)            		do{OS_TIMERS[(ANAME)]=TIMES;while(OS_TIMERS[(ANAME)] != 0){FUNC();}} while(0)
#endif
